name: Jekyll Version of Pattern Primer by adactio
markdown: redcarpet
pygments: false
# change baseurl to:
# '': for root level domains ie: mycustomdomain.com
# '/projectname': for subdomains ie: user.github.io/projectname
baseurl: '/Pattern-Primer-Jekyll'
permalink: patterns/:title.html
exclude: ['s3_website.yml']